# Conservative Model

## Overview
The Conservative model is OddsFlow’s lower-volatility model style.

It is designed to prioritize signal stability and quality over frequency, focusing on situations where pricing inefficiencies appear more controlled and less volatile.

The Conservative model does **not** predict match scores.  
It estimates fair odds and identifies mispriced bookmaker odds with a cautious risk profile.

---

## Risk profile
- Lower volatility
- Lower variance
- Focus on signal robustness
- Designed for steadier performance characteristics

This model may generate fewer signals compared to more aggressive styles.

---

## Typical market fit
The Conservative model is commonly applied to:
- **1X2 (Moneyline)**
- Selected **Asian Handicap** markets

Market fit can vary by league and conditions.  
Verification should always be done at the model + market level.

---

## How signals are published
Signals generated by the Conservative model are published with the following fields:
- `model_style = CONSERVATIVE`
- Market odds (book odds)
- OddsFlow fair odds estimate
- Edge percentage
- Confidence indicator
- Timestamp (UTC, published before kickoff)

---

## Verification
Performance of the Conservative model can be independently verified by:
- Filtering historical logs where `model_style = CONSERVATIVE`
- Reviewing performance by market type and sample size
- Comparing book odds vs fair odds over time

All signals are included in the public log without cherry-picking.

---

## Important notes
The Conservative model does not guarantee outcomes.  
It reflects a lower-risk approach to detecting pricing inefficiencies in football betting markets.
